language: python
python:
- '2.7'
before_install:
 - sudo apt-get install libhdf5-serial-dev
install:
- pip install .
- pip install mock
- pip install coveralls
script: coverage run --source=pytroll-aapp-runner setup.py test
after_success: coveralls